apiVersion: v1
kind: Secret

metadata:
  name: enterprise-cicd-secret
  namespace: enterprise-cicd

  labels:
    app: enterprise-cicd-platform

type: Opaque

stringData:

  # Demo secret only
  APP_SECRET: "change-me-in-production"
